### ISSUE TITLE
Problem with space #42

### ISSUE THREAD

**Issue by GerbenCdg** [Juansero29/CSharp#1]
Hello, I would like to report a problem concerning the space #42 in Board.cs, at the index 42 of the array Spaces is instanciated a BlockedSpace, while there should be instanciated a TeleportSpace instead. Let me remind you this rule of the Goose game  : 
"Celui qui tombe sur la case 42 correspondant au labyrinthe retournera obligatoirement à la case 30"

It should be :
`   if (i == 42)
                {
                    Spaces[i] = new TeleportSpace();
                }`

instead of 

`   if (i == 42)
                {
                    Spaces[i] = new BlockedSpace();
                }`

Thank you for correcting the issue.

**Comment by Juansero29** [comment]
Hi, the issue has been reported and will be fixed in the next commit. Thank you for your collaboration! ;)
